### PR TITLE
Update README.md add two sites built by nuxt

### PR DESCRIPTION
**Pull request by jhd4tmr**
Two sites are built by nuxt ssr. Glad to share the experience of using nuxt to build the frontend or even the backend of a website.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks!

**Comment by frederic117** [comment]
One more site with nuxt :)
insiders.football
For the love of ⚽ and nuxt :)

**Comment by pi0** [comment]
@frederic117 do you wish to also list it?

**Comment by frederic117** [comment]
Yes :)

**Comment by pi0** [comment]
So make a PR please :)

**Pull request merged**
