### PR TITLE
Added sweetalert2 module

### PR DESCRIPTION
**Pull request by ImreC**

### CODE REVIEW

**Comment by ImreC** [comment]
Just commited the updates

**Comment by ImreC** [comment]
@limonte, I wrote this two days ago because I needed it for a project. Decided to share it because seemed handy. It basically registers vue-sweetalert2 as a nuxt module and adds general options through swal.mixin. Approximately 35 lines of code. Obviously could write tests, but seemed like overdoing it for the level of complexity.

**Comment by limonte** [comment]
> Approximately 35 lines of code. Obviously could write tests, but seemed like overdoing it for the level of complexity.

If it's not tested, it's broken.

**Pull request merged**
