### PR TITLE
Added empire-admin template repository

### PR DESCRIPTION
**Pull request by zeknoss**
Please feel free to give your comments and suggestions in the project repository, spread the love!

### CODE REVIEW

**Comment by Geminii** [comment]
Hi @zeknoss 👋 
Really sorry for the delay 😥

Some question about project still in progress ?

It's not a module, so you need to move into the "showcase" section 👍

**Comment by zeknoss** [comment]
Hi @Geminii,
2 years of delay man :) I became discouraged when no one bat an eyelash to the project but yeah, it's "kinda" in progress still.

**Comment by zeknoss** [comment]
Yes, of  course. Thank you Jimmy! @Geminii

**Comment by Geminii** [comment]
@zeknoss done 👍

**Comment by zeknoss** [comment]
oh crap, sorry @Geminii man, I was caught deep in work all the week, please forgive me :(

**Comment by Geminii** [comment]
> oh crap, sorry @Geminii man, I was caught deep in work all the week, please forgive me :(

Not a problem 👍  
It's now integrated 😀

**Comment by zeknoss** [comment]
Thanks man, much appreciated!

**Pull request merged**
