### PR TITLE
Fix issues from awesome-lint

### PR DESCRIPTION
**Pull request by manniL**
related: https://github.com/sindresorhus/awesome/pull/1100#issuecomment-408628551, https://github.com/sindresorhus/awesome/pull/1420#issuecomment-433685022

### CODE REVIEW

**Comment by manniL** [comment]
Dead links were from:
* @dotneet (#31)
* @kavalcante (https://github.com/nuxt-community/awesome-nuxt/commit/c03654cd3460cdeef4cf919ad859f65fe50bf343)
* @moso (https://github.com/nuxt-community/awesome-nuxt/commit/5aeaf6b3f030ef762ed8de92667adc876856410f)
* deleted user (https://github.com/nuxt-community/awesome-nuxt/commit/fe288fb9c0c63f83a5612ce51a787a5db70277d9)

Please resubmit your page when it's back online.

**Comment by moso** [comment]
My link isn't dead. Just having some issues with nginx. Should be up and running now.

**Comment by manniL** [comment]
@moso I just checked it, so bad timing I guess :see_no_evil: Will restore it in the PR :+1:

**Comment by kavalcante** [comment]
@manniL My link isn't dead too. This weekend we have an issue with the DNS. In this week will be everything up again!

**Comment by manniL** [comment]
@kavalcante Will change ;)

**Comment by limichange** [comment]
🙇‍♂️ 勤劳的小伙子

**Comment by manniL** [comment]
@limichange I think that PR is ready 4 review ☺️

**Pull request merged**
