### PR TITLE
Add nuxt-sanity community module

### PR DESCRIPTION
**Pull request by vicbergquist**

### CODE REVIEW

**Comment by pi0** [comment]
Hi @vicbergquist & nice module! If you are interested we can transfer the project to be an official nuxt-community project and release under `@nuxtjs/`.

Also would be a good idea to add a 1-2 line description in your repository to showcase it or provide a demo that how it works.

**Comment by vicbergquist** [comment]
Hi @pi0, thank you!

That would be awesome!
I actually wrote some documentation for it :) https://nuxt-sanity.netlify.com
The readme also includes some information! https://github.com/vicbergquist/nuxt-sanity

**Comment by pi0** [comment]
Oops sorry, I missed that. BTW I've sent you an [invitation](https://github.com/orgs/nuxt-community) so you can transfer. For publishing access under `@nuxtjs/sanity`, just ping me in an issue or discord. Alternatively, maybe we can publish under `@sanity/nuxt`?

**Comment by pi0** [comment]
@vicbergquist Hi! Any updates?

**Comment by pi0** [comment]
Merging as-is :) Please ping us if wanted to move to official namespace.

**Pull request merged**
